//
// Copyright(C) 1993-1996 Id Software, Inc.
// Copyright(C) 1993-2008 Raven Software
// Copyright(C) 2005-2014 Simon Howard
// Copyright(C) 2016-2025 Julia Nechaevskaya
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//


// MN_menu.c ---------------------------------------------------------------

#define PRESSKEY	"pressione uma tecla."
#define PRESSYN		"pressione s ou n."
#define TXT_PAUSED	"PAUSADO"
#define QUITMSG		"tem certeza que deseja sair\ndeste grande jogo?"
#define LOADNET		"voce nao pode carregar um jogo em rede!\n\n"PRESSKEY
#define QLOADNET	"voce nao pode usar o carregamento rapido em um jogo em rede!\n\n"PRESSKEY
#define QSAVESPOT	"voce ainda nao escolheu um espaco para salvar rapidamente!\n\n"PRESSKEY
#define SAVEDEAD 	"voce nao pode salvar se nao estiver jogando!\n\n"PRESSKEY
#define QSPROMPT 	"salvar rapidamente sobre o seu jogo chamado\n\n'%s'?\n\n"PRESSYN
#define QLPROMPT	"voce quer carregar rapidamente o jogo chamado"\
					"\n\n'%s'?\n\n"PRESSYN
#define NEWGAME		"voce nao pode iniciar um novo jogo\n"\
					"enquanto estiver em uma partida em rede.\n\n"PRESSKEY
#define MSGOFF		"Mensagens DESLIGADAS"
#define MSGON		"Mensagens LIGADAS"
#define NETEND		"voce nao pode encerrar um jogo em rede!\n\n"PRESSKEY
#define ENDGAME		"tem certeza que deseja encerrar a partida?\n\n"PRESSYN
#define DOSY		"(pressione s para sair para o dos.)"
#define TXT_GAMMA_LEVEL_OFF	"CORRECAO DE GAMA DESLIGADA"
#define TXT_GAMMA_LEVEL_1	"CORRECAO DE GAMA NIVEL 1"
#define TXT_GAMMA_LEVEL_2	"CORRECAO DE GAMA NIVEL 2"
#define TXT_GAMMA_LEVEL_3	"CORRECAO DE GAMA NIVEL 3"
#define TXT_GAMMA_LEVEL_4	"CORRECAO DE GAMA NIVEL 4"
#define	EMPTYSTRING	"espaco vazio"

// P_inter.c ---------------------------------------------------------------

// Mana

#define TXT_MANA_1				"MANA AZUL"
#define TXT_MANA_2				"MANA VERDE"
#define TXT_MANA_BOTH			"MANA COMBINADA"

// Keys

#define	TXT_KEY_STEEL		"CHAVE DE ACO"
#define	TXT_KEY_CAVE		"CHAVE DA CAVERNA"
#define	TXT_KEY_AXE			"CHAVE DO MACHADO"
#define	TXT_KEY_FIRE		"CHAVE DE FOGO"
#define	TXT_KEY_EMERALD		"CHAVE DE ESMERALDA"
#define	TXT_KEY_DUNGEON		"CHAVE DA MASMORRA"
#define	TXT_KEY_SILVER		"CHAVE DE PRATA"
#define	TXT_KEY_RUSTED		"CHAVE ENFERRUJADA"
#define	TXT_KEY_HORN		"CHAVE DE CHIFRE"
#define	TXT_KEY_SWAMP		"CHAVE DO PANTANO"
#define TXT_KEY_CASTLE		"CHAVE DO CASTELO"

// Artifacts

#define TXT_ARTIINVULNERABILITY		"ICONE DO DEFENSOR"
#define TXT_ARTIHEALTH				"FRASCO DE QUARTZO"
#define TXT_ARTISUPERHEALTH			"URNA MISTICA"
#define TXT_ARTISUMMON				"SERVO DAS TREVAS"
#define TXT_ARTITORCH				"TOCHA"
#define TXT_ARTIEGG					"PORCALIZADOR"
#define TXT_ARTIFLY					"ASAS DA IRA"
#define TXT_ARTITELEPORT			"ARTEFATO DO CAOS"
#define TXT_ARTIPOISONBAG			"BOMBA DE VENENO"
#define TXT_ARTITELEPORTOTHER		"ARTEFATO DO BANIMENTO"
#define TXT_ARTISPEED				"BOTAS DA VELOCIDADE"
#define TXT_ARTIBOOSTMANA			"CRATERA DE PODER"
#define TXT_ARTIBOOSTARMOR			"BRACELETES DE DRAGAO"
#define TXT_ARTIBLASTRADIUS			"DISCO DA REPULSAO"
#define TXT_ARTIHEALINGRADIUS		"ENCANTAMENTO MISTICO"

// Puzzle artifacts

#define TXT_ARTIPUZZSKULL			"CRANIO DE YORICK"
#define TXT_ARTIPUZZGEMBIG			"CORACAO DE D'SPARIL"
#define TXT_ARTIPUZZGEMRED			"PLANETA DE RUBI"
#define TXT_ARTIPUZZGEMGREEN1		"PLANETA DE ESMERALDA"
#define TXT_ARTIPUZZGEMGREEN2		"PLANETA DE ESMERALDA"
#define TXT_ARTIPUZZGEMBLUE1		"PLANETA DE SAFIRA"
#define TXT_ARTIPUZZGEMBLUE2		"PLANETA DE SAFIRA"
#define TXT_ARTIPUZZBOOK1			"CODICE DEMONIACO"
#define TXT_ARTIPUZZBOOK2			"LIBER OSCURA"
#define TXT_ARTIPUZZSKULL2			"MASCARA DE CHAMA"
#define TXT_ARTIPUZZFWEAPON			"SELO DA ALABARDA"
#define TXT_ARTIPUZZCWEAPON			"RELIQUIA SAGRADA"
#define TXT_ARTIPUZZMWEAPON			"SIGILO DO MAGO"
#define TXT_ARTIPUZZGEAR			"ENGRENAGEM DE RELOGIO"
#define TXT_USEPUZZLEFAILED			"VOCE NAO PODE USAR ISTO AQUI"

// Items

#define TXT_ITEMHEALTH			"FRASCO DE CRISTAL"
#define TXT_ITEMBAGOFHOLDING	"SACOLA DE ARMAZENAMENTO"
#define TXT_ITEMSHIELD1			"ESCUDO DE PRATA"
#define TXT_ITEMSHIELD2			"ESCUDO ENCANTADO"
#define TXT_ITEMSUPERMAP		"PERGAMINHO DO MAPA"
#define TXT_ARMOR1				"ARMADURA DE MALHA"
#define TXT_ARMOR2				"ESCUDO DO FALCAO"
#define TXT_ARMOR3				"ELMO DE PLATINA"
#define TXT_ARMOR4				"AMULETO DE PROTECAO"

// Weapons

#define TXT_WEAPON_F2			"MACHADO DE TIMON"
#define TXT_WEAPON_F3			"MARTELO DA RETRIBUICAO"
#define TXT_WEAPON_F4			"QUIETUS MONTADO"
#define TXT_WEAPON_C2			"CAJADO DA SERPENTE"
#define TXT_WEAPON_C3			"TEMPESTADE DE FOGO"
#define TXT_WEAPON_C4			"WRAITHVERGE MONTADO"
#define TXT_WEAPON_M2			"FRAGMENTOS DE GELO"
#define TXT_WEAPON_M3			"ARCO DA MORTE"
#define TXT_WEAPON_M4			"BLOODSCOURGE MONTADO"
#define TXT_QUIETUS_PIECE		"FRAGMENTO DE QUIETUS"
#define TXT_WRAITHVERGE_PIECE	"FRAGMENTO DE WRAITHVERGE"
#define TXT_BLOODSCOURGE_PIECE	"FRAGMENTO DE BLOODSCOURGE"

// SB_bar.c ----------------------------------------------------------------

#define TXT_CHEATGODON			"MODO DEUS LIG."
#define TXT_CHEATGODOFF			"MODO DEUS DESL."
#define TXT_CHEATNOCLIPON		"MODO ATRAVESSAR LIG."
#define TXT_CHEATNOCLIPOFF		"MODO ATRAVESSAR DESL."
#define TXT_CHEATWEAPONS		"TODAS AS ARMAS"
#define TXT_CHEATWPNSKEYS		"TODAS AS ARMAS E CHAVES"
#define TXT_CHEATHEALTH			"VIDA COMPLETA"
#define TXT_CHEATKEYS			"TODAS AS CHAVES"
#define TXT_CHEATSOUNDON		"DEBUG DE SOM LIG."
#define TXT_CHEATSOUNDOFF		"DEBUG DE SOM DESL."
#define TXT_CHEATTICKERON		"TICKER LIG."
#define TXT_CHEATTICKEROFF		"TICKER DESL."
#define TXT_CHEATARTIFACTS3		"TODOS OS ARTEFATOS"
#define TXT_CHEATARTIFACTSFAIL	"CODIGO INVALIDO"
#define TXT_CHEATWARP			"PULO DE FASE"
#define TXT_CHEATSCREENSHOT		"CAPTURA DE TELA"
#define TXT_CHEATIDDQD			"TENTANDO TRAPACEAR, HEIN? AGORA VOCE MORRE!"
#define TXT_CHEATIDKFA			"TRAPACEIRO - VOCE NAO MERECE ARMAS"
#define TXT_CHEATBADINPUT		"CODIGO INVALIDO"
#define TXT_CHEATNOMAP			"NAO FOI POSSIVEL ENCONTRAR O MAPA"

// G_game.c ----------------------------------------------------------------

#define TXT_GAMESAVED			"JOGO SALVO"

// M_misc.c ----------------------------------------------------------------

#define HUSTR_CHATMACRO1 "Estou pronto pra detonar!"
#define HUSTR_CHATMACRO2 "Estou bem."
#define HUSTR_CHATMACRO3 "Nao estou me sentindo bem!"
#define HUSTR_CHATMACRO4 "Ajuda!"
#define HUSTR_CHATMACRO5 "Voce e um lixo!"
#define HUSTR_CHATMACRO6 "Na proxima, seu canalha..."
#define HUSTR_CHATMACRO7 "Vem ca!"
#define HUSTR_CHATMACRO8 "Deixa que eu cuido disso."
#define HUSTR_CHATMACRO9 "Sim"
#define HUSTR_CHATMACRO0 "Nao"

// AM_map.c ----------------------------------------------------------------

#define AMSTR_FOLLOWON		"MODO SEGUIR LIG."
#define AMSTR_FOLLOWOFF		"MODO SEGUIR DESL."

#define AMSTR_GRIDON		"GRADE LIGADA"
#define AMSTR_GRIDOFF		"GRADE DESLIGADA"

#define AMSTR_MARKEDSPOT	"LOCAL MARCADO"
#define AMSTR_MARKCLEARED	"MARCA REMOVIDA"
#define AMSTR_MARKSCLEARED	"TODAS AS MARCAS REMOVIDAS"

// -----------------------------------------------------------------------------
// [JN] ID-specific strings.
// -----------------------------------------------------------------------------

#define ID_EXTHUD_ON        "HUD EXTENDIDO LIG."
#define ID_EXTHUD_OFF       "HUD EXTENDIDO DESL."

#define ID_SPECTATOR_ON     "MODO ESPECTADOR LIG."
#define ID_SPECTATOR_OFF    "MODO ESPECTADOR DESL."

#define ID_FREEZE_ON        "MODO CONGELAR LIG."
#define ID_FREEZE_OFF       "MODO CONGELAR DESL."
#define ID_FREEZE_NA_R      "CONGELAR NAO DISPONIVEL NA GRAVACAO DE DEMO"
#define ID_FREEZE_NA_P      "CONGELAR NAO DISPONIVEL NA REPRODUCAO DE DEMO"
#define ID_FREEZE_NA_N      "CONGELAR NAO DISPONIVEL EM JOGO MULTIJOGADOR"

#define ID_NOTARGET_ON      "MODO SEM ALVO LIG."
#define ID_NOTARGET_OFF     "MODO SEM ALVO DESL."
#define ID_NOTARGET_NA_R    "SEM ALVO NAO DISPONIVEL NA GRAVACAO DE DEMO"
#define ID_NOTARGET_NA_P    "SEM ALVO NAO DISPONIVEL NA REPRODUCAO DE DEMO"
#define ID_NOTARGET_NA_N    "SEM ALVO NAO DISPONIVEL EM JOGO MULTIJOGADOR"

#define ID_BUDDHA_ON        "MODO BUDA LIG."
#define ID_BUDDHA_OFF       "MODO BUDA DESL."
#define ID_BUDDHA_NA_R      "BUDA NAO DISPONIVEL NA GRAVACAO DE DEMO"
#define ID_BUDDHA_NA_P      "BUDA NAO DISPONIVEL NA REPRODUCAO DE DEMO"
#define ID_BUDDHA_NA_N      "BUDA NAO DISPONIVEL EM JOGO MULTIJOGADOR"

#define ID_AUTOMAPROTATE_ON     "MODO GIRAR LIG."
#define ID_AUTOMAPROTATE_OFF    "MODO GIRAR DESL."
#define ID_AUTOMAPOVERLAY_ON    "MODO SOBREPOSICAO LIG."
#define ID_AUTOMAPOVERLAY_OFF   "MODO SOBREPOSICAO DESL."
#define ID_AUTOMAPMOUSEPAN_ON   "MODO PANORAMICA COM MOUSE LIG."
#define ID_AUTOMAPMOUSEPAN_OFF  "MODO PANORAMICA COM MOUSE DESL."

#define ID_AUTORUN_ON      "SEMPRE CORRER LIG."
#define ID_AUTORUN_OFF     "SEMPRE CORRER DESL."

#define ID_MLOOK_ON        "OLHAR COM O MOUSE LIG."
#define ID_MLOOK_OFF       "OLHAR COM O MOUSE DESL."

#define ID_NOVERT_ON       "MOVIMENTO VERTICAL DO MOUSE DESL."
#define ID_NOVERT_OFF      "MOVIMENTO VERTICAL DO MOUSE LIG."

#define ID_SECRET_FOUND     "UM SEGREDO FOI REVELADO!"

#define DETAILHI    "DETALHE ALTO"
#define DETAILLO    "DETALHE BAIXO"

#define GAMMALVL_N050   "CORRECAO DE GAMA NIVEL -0.50"
#define GAMMALVL_N055   "CORRECAO DE GAMA NIVEL -0.55"
#define GAMMALVL_N060   "CORRECAO DE GAMA NIVEL -0.60"
#define GAMMALVL_N065   "CORRECAO DE GAMA NIVEL -0.65"
#define GAMMALVL_N070   "CORRECAO DE GAMA NIVEL -0.70"
#define GAMMALVL_N075   "CORRECAO DE GAMA NIVEL -0.75"
#define GAMMALVL_N080   "CORRECAO DE GAMA NIVEL -0.80"
#define GAMMALVL_N085   "CORRECAO DE GAMA NIVEL -0.85"
#define GAMMALVL_N090   "CORRECAO DE GAMA NIVEL -0.90"
#define GAMMALVL_N095   "CORRECAO DE GAMA NIVEL -0.95"
#define GAMMALVL_OFF    "CORRECAO DE GAMA DESLIGADA"
#define GAMMALVL_010    "CORRECAO DE GAMA NIVEL 0.1"
#define GAMMALVL_020    "CORRECAO DE GAMA NIVEL 0.2"
#define GAMMALVL_030    "CORRECAO DE GAMA NIVEL 0.3"
#define GAMMALVL_040    "CORRECAO DE GAMA NIVEL 0.4"
#define GAMMALVL_050    "CORRECAO DE GAMA NIVEL 0.5"
#define GAMMALVL_060    "CORRECAO DE GAMA NIVEL 0.6"
#define GAMMALVL_070    "CORRECAO DE GAMA NIVEL 0.7"
#define GAMMALVL_080    "CORRECAO DE GAMA NIVEL 0.8"
#define GAMMALVL_090    "CORRECAO DE GAMA NIVEL 0.9"
#define GAMMALVL_100    "CORRECAO DE GAMA NIVEL 1.0"
#define GAMMALVL_110    "CORRECAO DE GAMA NIVEL 1.1"
#define GAMMALVL_120    "CORRECAO DE GAMA NIVEL 1.2"
#define GAMMALVL_130    "CORRECAO DE GAMA NIVEL 1.3"
#define GAMMALVL_140    "CORRECAO DE GAMA NIVEL 1.4"
#define GAMMALVL_150    "CORRECAO DE GAMA NIVEL 1.5"
#define GAMMALVL_160    "CORRECAO DE GAMA NIVEL 1.6"
#define GAMMALVL_170    "CORRECAO DE GAMA NIVEL 1.7"
#define GAMMALVL_180    "CORRECAO DE GAMA NIVEL 1.8"
#define GAMMALVL_190    "CORRECAO DE GAMA NIVEL 1.9"
#define GAMMALVL_200    "CORRECAO DE GAMA NIVEL 2.0"
#define GAMMALVL_220    "CORRECAO DE GAMA NIVEL 2.2"
#define GAMMALVL_240    "CORRECAO DE GAMA NIVEL 2.4"
#define GAMMALVL_260    "CORRECAO DE GAMA NIVEL 2.6"
#define GAMMALVL_280    "CORRECAO DE GAMA NIVEL 2.8"
#define GAMMALVL_300    "CORRECAO DE GAMA NIVEL 3.0"
#define GAMMALVL_320    "CORRECAO DE GAMA NIVEL 3.2"
#define GAMMALVL_340    "CORRECAO DE GAMA NIVEL 3.4"
#define GAMMALVL_360    "CORRECAO DE GAMA NIVEL 3.6"
#define GAMMALVL_380    "CORRECAO DE GAMA NIVEL 3.8"
#define GAMMALVL_400    "CORRECAO DE GAMA NIVEL 4.0"

#define ID_OST_NA          "MUSICA REMASTERIZADA NAO CARREGADA"
#define ID_OST_NA_1        "HEXEN[MUS[REMIX.WAD E"
#define ID_OST_NA_2        "HEXEN[MUS[ORIG.WAD NAO FORAM CARREGADOS"
#define ID_OST_OFF         "TRILHA SONORA PREFERIDA: DESLIGADA"
#define ID_OST_REMIX       "TRILHA SONORA PREFERIDA: REMIX"
#define ID_OST_ORIGINAL    "TRILHA SONORA PREFERIDA: ORIGINAL"
